language: android

jdk: oraclejdk8

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/android/
android:
  components:
    - tools
    - platform-tools
    - android-26
    - build-tools-27.0.3
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - android-sdk-license-.+
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-26"
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - ./gradlew check

notifications:
  email: false