language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=26
    - ANDROID_ABI=armeabi-v7a

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/android/
android:
  components:
    - tools
    - platform-tools
    - android-$ANDROID_TARGET
    - build-tools-27.0.3
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - android-sdk-license-.+
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-$ANDROID_API --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false